services:
  mcpo:
    build: .
    #image: webui-mcpo:v1.2
    #container_name: webui-mcpo
    ports:
      - "8000:8000"
    volumes:
      - ./mcpo:/opt/mcpo
    environment:
      - MCPO_API_KEY=${MCPO_API_KEY}
    restart: unless-stopped
