services:
  mcpo:
    build:
      context: .
      no_cache: true
    ports:
      - "8000:8000"
    volumes:
      - ./mcpo:/opt/mcpo
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: unless-stopped
